### ISSUE TITLE
Dies in classification tree

### ISSUE THREAD

**Issue by ptarjan** [ruby-prof/ruby-prof#205]
When running a profile of our code, I'm getting:

```
$ ruby-prof a.rb
.. my code runs ..
Measure Mode: wall_time
Thread ID: 70096769114560
Fiber ID: 70096777452700
Total: 48.806793
Sort by: self_time

 %self      total      self      wait     child     calls  name
  6.89      3.364     3.364     0.000     0.000    42398   Module#name
  4.56      2.226     2.226     0.000     0.000  1562304   Kernel#hash
  4.33      2.355     2.113     0.000     0.241       34   <Module::Marshal>#load
  2.72      1.325     1.325     0.000     0.000   625508   BasicObject#!
  2.59      1.392     1.264     0.000     0.128   498591   Hash#[]=
.. lost of timings ..

/Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/bundler/gems/interchange-79bb282c3e37/lib/interchange/framework/classification_tree.rb:177:in `_stringify': undefined method `map' for nil:NilClass (NoMethodError)
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/bundler/gems/interchange-79bb282c3e37/lib/interchange/framework/classification_tree.rb:135:in `inspect'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/abstract_printer.rb:46:in `full_name'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/abstract_printer.rb:46:in `method_name'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/flat_printer_with_line_numbers.rb:48:in `block (2 levels) in print_methods'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/flat_printer_with_line_numbers.rb:46:in `each'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/flat_printer_with_line_numbers.rb:46:in `block in print_methods'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/flat_printer_with_line_numbers.rb:20:in `each'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/flat_printer_with_line_numbers.rb:20:in `print_methods'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/abstract_printer.rb:75:in `print_thread'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/abstract_printer.rb:69:in `block in print_threads'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/abstract_printer.rb:68:in `each'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/abstract_printer.rb:68:in `print_threads'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/abstract_printer.rb:64:in `print'
        from /Users/pt/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/bin/ruby-prof:335:in `block in <top (required)>'
```

It looks like one of our methods is weird and breaks an assumption you're making?

(Other printers also have the problem, some earlier than others)

**Comment by skaes** [comment]
It does not crash in ruby-prof, as you can see from the trace you provided. It crashes in some version of a gem called interchange, which apparently monkey patches the inspect method.

Closing this, it's not ruby-prof related.
