### ISSUE TITLE
ruby-prof hanging, consuming 100% CPU (single core)

### ISSUE THREAD

**Issue by duncan-bayne** [ruby-prof/ruby-prof#212]
I'm running ruby-prof via rspec-prof:

```
RSPEC_PROFILE=all rspec spec/controllers/api/v1/my/wombles/womble_controller_spec.rb
```

The spec takes ~ 10 minutes to run normally (hence why I'm profiling it :angry:).  When I profile it, though, it never finishes.  The spec has been running for nearly two hours at this point, and is consuming 100% CPU time on one core:

```
PID   USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
12710 duncan    20   0 3263836 2.805g  15772 R 106.7 18.0 115:24.89 ruby
```

I can extract a Ruby backtrace by attaching w/ gdb, and it looks as though it's locked up writing the profile:

```
$ sudo gdb ~/.rbenv/versions/2.2.2/bin/ruby -p 12710
GNU gdb (Ubuntu 7.12.50.20170314-0ubuntu1) 7.12.50.20170314-git
...
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000055aa066b1194 in vm_exec_core (th=th@entry=0x55aa07d1f5f0, initial=initial@entry=0) at vm.inc:2468
2468    vm.inc: No such file or directory.
(gdb) call rb_backtrace()

   from /home/duncan/.rbenv/versions/2.2.2/bin/rspec:23:in `<main>'
        from /home/duncan/.rbenv/versions/2.2.2/bin/rspec:23:in `load'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:87:in `run'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:77:in `report'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1837:in `with_suite_hooks'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1880:in `run_suite_hooks'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1880:in `each'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1882:in `block in run_suite_hooks'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:357:in `run'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:443:in `instance_exec'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:443:in `instance_exec'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:68:in `block (2 levels) in <top (required)>'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:46:in `save_to'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:46:in `open'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:48:in `block in save_to'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/graph_html_printer.rb:39:in `print'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
        from (erb):76:in `print'
        from (erb):76:in `each'
        from (erb):98:in `block in print'
        from (erb):98:in `reverse_each'
        from (erb):139:in `block (2 levels) in print'
        from (erb):139:in `sort_by'
        from (erb):139:in `each'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/aggregate_call_info.rb:34:in `total_time'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/aggregate_call_info.rb:71:in `aggregate_roots'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/aggregate_call_info.rb:61:in `roots'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:64:in `roots_of'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:64:in `any?'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:64:in `block in roots_of'
        from /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:54:in `descendent_of'
```

Relevant versions of things:

```
ruby-prof  0.16.2
rspec-prof 0.0.7
rspec      3.5.0
ruby       2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```

I'm very happy to assist with debugging this in any way necessary, as I'm quite keen to be able to profile these specs.

**Comment by rdp** [comment]
Is it an infinite loop?

**Comment by skaes** [comment]
I have never benchmarked something which runs for 10 minutes without ruby-prof.

I strongly suggest you follow on the footsteps of Caesar and Napoleon and break down the problem into smaller parts.

That said: how do you expect us to help here?

**Comment by duncan-bayne** [comment]
@rdp Probably not; it completes eventually when run without profiling. 

@skaes Thanks - I hadn't realised 10 minutes was a large run; I'll see if I can produce a subset. Re. what I expected, I was hoping to be able to help you address what I thought was a bug, hence my offer to assist w/ debugging.

**Comment by skaes** [comment]
@duncan-bayne We can't really make debugging progress without the code which causes the problem, I can only provide some hints as to how I might approach the situation.

1. I noticed you're using a rather old ruby (2.2.2). Try upgrading to 2.3.3 or 2.4.1 and see whether the bug goes away.
2. Try using the master branch of ruby-prof and see wether the problem vanishes.
3. Remove half of your code in the controller you're testing and see whether the problem goes away. If it does, try the other half and see whether it causes the problem.

HTH

**Comment by duncan-bayne** [comment]
@skaes Thanks - I'll work through those steps, see if I can narrow down a simple repro case on current Ruby.  It may be challenging though; the reason I was hoping to profile this code is that it's slow, complicated legacy code :)

**Comment by skaes** [comment]
Closing the issue as it seems not possible to make progress here.
