### ISSUE TITLE
Profiling a script with merge_fibers=true raises SystemStackError: stack level too deep from RubyProf::CallInfo#detect_recursion

### ISSUE THREAD

**Issue by SpComb** [ruby-prof/ruby-prof#220]
Using `RubyProf.profile(merge_fibers: true)` to profile some [`Celluloid`](https://github.com/celluloid/celluloid) based code that makes extensive use of fibers, I'm encountering some recursion errors from `ruby-prof` (version 0.16.2) when trying to use `merge_fibers: true` to view combined profiling results for each actor thread.

Here's a minimal repro case from: https://gist.github.com/SpComb/a3cb9cb9842719c4d5cffce72a71d9fc#file-ruby-profile-celluloid-fibers-rb

```ruby
#!/usr/bin/env ruby

require 'celluloid/current'
require 'ruby-prof'

class TestSubject
  include Celluloid

  def ping
    sleep 0.1
  end
end

test_subject = TestSubject.new

results = RubyProf.profile(merge_fibers: true) do
  wait_futures = (1..1000).map{|i| test_subject.future.ping() }
  wait_futures.map{|f| f.value }
end

RubyProf::FlatPrinter.new(results).print(STDOUT)
```

Resulting crash from ruby-prof:

```
/home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:17:in `block in detect_recursion': stack level too deep (SystemStackError)
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:16:in `each'
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:16:in `detect_recursion'
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:17:in `block in detect_recursion'
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:16:in `each'
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:16:in `detect_recursion'
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:17:in `block in detect_recursion'
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:16:in `each'
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/call_info.rb:16:in `detect_recursion'
	 ... 11548 levels...
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/profile.rb:9:in `post_process'
	from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/compatibility.rb:147:in `profile'
from /home/kontena/.gem/ruby/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/compatibility.rb:147:in `profile'
```

**Comment by SpComb** [comment]
BTW I also noticed that the `RubyProf.profile do ...` seems to swallow up any exceptions raised by the block, discarding them silently and just showing profiling results for the error case... had to add explicit error rescue => logging within the block to actually get that repro case to work.

**Comment by skaes** [comment]
Thx for the report. I can reproduce the crash on my dev machine. Will try to fix.

**Comment by skaes** [comment]
Found it, fix is on master. It's a wonder this kind of segfault didn't happen more often. See https://github.com/ruby-prof/ruby-prof/commit/ecae0bd92e57dfee76a70c973fae2dd5ee90621e.
