### ISSUE TITLE
abdul010

### ISSUE THREAD

**Issue by abdul010** [ruby-prof/ruby-prof#233]
Hi     I have this issue how can i fix it pleas ???
l.zip.ZipException: zip file is empty
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:293)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:291)
	... 3 more
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
[*] Decompiling payload APK..
apk-embed-payload.rb:189:in `initialize': No such file or directory @ rb_sysopen - original/AndroidManifest.xml (Errno::ENOENT)
	from apk-embed-payload.rb:189:in `open'
	from apk-embed-payload.rb:189:in `<main>'

**Comment by skaes** [comment]
I think you wanted to open this issue on another project.
