### ISSUE TITLE
print': wrong number of arguments (given 2, expected 0..1) (ArgumentError)

### ISSUE THREAD

**Issue by radome** [ruby-prof/ruby-prof#236]
Hello!

Got this error with ruby-prof-0.16.2. Everything works fine with 0.15.9.

```
/Users/ldrf/.rvm/gems/ruby-2.4.1/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:46:in `print': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance/ruby.rb:54:in `block (2 levels) in record'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance/ruby.rb:53:in `open'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance/ruby.rb:53:in `block in record'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance/ruby.rb:50:in `each'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance/ruby.rb:50:in `record'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance.rb:118:in `run_profile'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance.rb:71:in `block in _performance_run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance.rb:69:in `each'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance.rb:69:in `_performance_run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/rails-perftest-0.0.7/lib/rails/perftest/active_support/testing/performance.rb:52:in `run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:943:in `run_one_method'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:334:in `run_one_method'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:321:in `block (2 levels) in run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:320:in `each'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:320:in `block in run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:360:in `on_signal'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:347:in `with_info_handler'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:319:in `run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/test_unit/line_filtering.rb:9:in `run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:159:in `block in __run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:159:in `map'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:159:in `__run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:136:in `run'
	from /Users/ldrf/.rvm/gems/ruby-2.4.1/gems/minitest-5.11.1/lib/minitest.rb:63:in `block in autorun'
```

**Comment by seafr** [comment]
Check out my comment [here](https://github.com/rails/rails-perftest/issues/38#issuecomment-365991394) if you are using `rails-perftest`

**Comment by cfis** [comment]
Hi all, guess I'm going to close this since its a year old and I assume rails-perftest fixes the call. If I should do anything on the ruby-prof side let me know.
