### ISSUE TITLE
Segfault while trying to load marshalled data

### ISSUE THREAD

**Issue by dwarburt** [ruby-prof/ruby-prof#315]
When I'm trying to load a marshalled results object like in the documentation, I encounter a segmentation fault under ruby 2.7.1 (and also 3.1.2)

Here's my test program:

```
class Worker
  def fast
    5*5
  end
  def slow
    5000.times do
      99999999*999999999999
    end
  end
end

require 'ruby-prof'

# profile the code
RubyProf.start
j = Worker.new
j.fast
j.slow

result = RubyProf.stop

# print a flat profile to text
marshalled_data = Marshal.dump(result)
loaded_data = Marshal.load(marshalled_data)
printer = RubyProf::FlatPrinter.new(loaded_data)
printer.print(STDOUT)

```

And the output from the segfault is this

<details>
<summary>Segfault output</summary>

```
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/profile.rb:9: [BUG] Segmentation fault at 0x0000000000000008
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0010 p:---- s:0049 e:000048 CFUNC  :measure_mode
c:0009 p:0003 s:0045 e:000044 METHOD /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/profile.rb:9
c:0008 p:0010 s:0041 e:000038 METHOD /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:102
c:0007 p:0005 s:0034 e:000033 METHOD /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:96
c:0006 p:0006 s:0029 e:000028 BLOCK  /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:91 [FINISH]
c:0005 p:---- s:0025 e:000024 CFUNC  :each
c:0004 p:0008 s:0021 e:000020 METHOD /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:90
c:0003 p:0029 s:0017 e:000016 METHOD /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:66
c:0002 p:0130 s:0011 E:001ca8 EVAL   ./test_profile copy.rb:28 [FINISH]
c:0001 p:0000 s:0003 E:0011e0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
./test_profile copy.rb:28:in `<main>'
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:66:in `print'
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:90:in `print_threads'
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:90:in `each'
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:91:in `block in print_threads'
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:96:in `print_thread'
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:102:in `print_header'
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/profile.rb:9:in `measure_mode_string'
/home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/profile.rb:9:in `measure_mode'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f43605fe711 RBP: 0x0000559f90cae6d0 RSP: 0x00007fff86231db0
 RAX: 0x0000000000000000 RBX: 0x0000559f9101fb40 RCX: 0x00007f43605fe700
 RDX: 0x00007f435ecff180 RDI: 0x0000559f910496e8 RSI: 0x0000000000000000
  R8: 0x0000559f91023a60  R9: 0x00007fff86231d80 R10: 0x0000000000000000
 R11: 0x0000559f910496e8 R12: 0x00007f435edfee18 R13: 0x0000000055550083
 R14: 0x0000559f91023a60 R15: 0x0000000000000000 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(rb_vm_bugreport+0x4f7) [0x7f43604b12a7]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(rb_bug_for_fatal_signal+0xeb) [0x7f43602d1f4b]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(sigsegv+0x4d) [0x7f436040fabd]
[0x7f435fe42520]
[0x7f43605fe711]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(vm_call_cfunc+0x130) [0x7f43604898e0]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(vm_exec_core+0x177) [0x7f43604964f7]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(rb_vm_exec+0x177) [0x7f436049c567]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(rb_yield+0x299) [0x7f43604aa1d9]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(rb_ary_each+0x3c) [0x7f4360239aec]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(vm_call_cfunc+0x130) [0x7f43604898e0]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(vm_exec_core+0x2c7) [0x7f4360496647]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(rb_vm_exec+0x611) [0x7f436049ca01]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(rb_ec_exec_node+0xb7) [0x7f43602d6b47]
/home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7(ruby_run_node+0x4c) [0x7f43602dc4fc]
/home/david/.rvm/rubies/ruby-2.7.1/bin/ruby(main+0x5f) [0x559f8fda517f]

-- Other runtime information -----------------------------------------------

* Loaded script: ./test_profile copy.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 ruby2_keywords.rb
    5 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
    6 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
    7 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/rbconfig.rb
    8 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/compatibility.rb
    9 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/defaults.rb
   10 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/deprecate.rb
   11 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/errors.rb
   12 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/unknown_command_spell_checker.rb
   13 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/exceptions.rb
   14 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/basic_specification.rb
   15 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/stub_specification.rb
   16 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/platform.rb
   17 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/util/list.rb
   18 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/version.rb
   19 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb
   20 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb
   21 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/util.rb
   22 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/dependency.rb
   23 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb
   24 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/monitor.so
   25 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb
   26 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb
   27 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_warn.rb
   28 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems.rb
   29 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/path_support.rb
   30 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/version.rb
   31 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/core_ext/name_error.rb
   32 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/levenshtein.rb
   33 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/jaro_winkler.rb
   34 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/spell_checker.rb
   35 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   36 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   37 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/spell_checkers/name_error_checkers.rb
   38 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/spell_checkers/method_name_checker.rb
   39 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/spell_checkers/key_error_checker.rb
   40 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/spell_checkers/null_checker.rb
   41 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/formatters/plain_formatter.rb
   42 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean/tree_spell_checker.rb
   43 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/did_you_mean.rb
   44 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/ext/ruby_prof/ruby_prof.so
   45 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/version.rb
   46 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/call_tree.rb
   47 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/compatibility.rb
   48 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/measurement.rb
   49 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/method_info.rb
   50 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/set.rb
   51 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/exclude_common_methods.rb
   52 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/profile.rb
   53 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/fileutils.rb
   54 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/etc.so
   55 /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tmpdir.rb
   56 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb
   57 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/thread.rb
   58 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof.rb
   59 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb
   60 /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/flat_printer.rb

* Process memory map:

559f8fda4000-559f8fda5000 r--p 00000000 fd:01 9962403                    /home/david/.rvm/rubies/ruby-2.7.1/bin/ruby
559f8fda5000-559f8fda6000 r-xp 00001000 fd:01 9962403                    /home/david/.rvm/rubies/ruby-2.7.1/bin/ruby
559f8fda6000-559f8fda7000 r--p 00002000 fd:01 9962403                    /home/david/.rvm/rubies/ruby-2.7.1/bin/ruby
559f8fda7000-559f8fda8000 r--p 00002000 fd:01 9962403                    /home/david/.rvm/rubies/ruby-2.7.1/bin/ruby
559f8fda8000-559f8fda9000 rw-p 00003000 fd:01 9962403                    /home/david/.rvm/rubies/ruby-2.7.1/bin/ruby
559f90cac000-559f91160000 rw-p 00000000 00:00 0                          [heap]
7f435b8b6000-7f435b8b7000 ---p 00000000 00:00 0 
7f435b8b7000-7f435b958000 rw-p 00000000 00:00 0 
7f435b958000-7f435b959000 ---p 00000000 00:00 0 
7f435b959000-7f435b9fa000 rw-p 00000000 00:00 0 
7f435b9fa000-7f435b9fb000 ---p 00000000 00:00 0 
7f435b9fb000-7f435ba9c000 rw-p 00000000 00:00 0 
7f435ba9c000-7f435ba9d000 ---p 00000000 00:00 0 
7f435ba9d000-7f435bb3e000 rw-p 00000000 00:00 0 
7f435bb3e000-7f435bb3f000 ---p 00000000 00:00 0 
7f435bb3f000-7f435bbe0000 rw-p 00000000 00:00 0 
7f435bbe0000-7f435bbe1000 ---p 00000000 00:00 0 
7f435bbe1000-7f435bc82000 rw-p 00000000 00:00 0 
7f435bc82000-7f435bc83000 ---p 00000000 00:00 0 
7f435bc83000-7f435bd24000 rw-p 00000000 00:00 0 
7f435bd24000-7f435bd25000 ---p 00000000 00:00 0 
7f435bd25000-7f435bdc6000 rw-p 00000000 00:00 0 
7f435bdc6000-7f435bdc7000 ---p 00000000 00:00 0 
7f435bdc7000-7f435be68000 rw-p 00000000 00:00 0 
7f435be68000-7f435be69000 ---p 00000000 00:00 0 
7f435be69000-7f435bf0a000 rw-p 00000000 00:00 0 
7f435bf0a000-7f435bf0b000 ---p 00000000 00:00 0 
7f435bf0b000-7f435bfac000 rw-p 00000000 00:00 0 
7f435bfac000-7f435bfad000 ---p 00000000 00:00 0 
7f435bfad000-7f435c04e000 rw-p 00000000 00:00 0 
7f435c04e000-7f435c04f000 ---p 00000000 00:00 0 
7f435c04f000-7f435c0f0000 rw-p 00000000 00:00 0 
7f435c0f0000-7f435c0f1000 ---p 00000000 00:00 0 
7f435c0f1000-7f435c192000 rw-p 00000000 00:00 0 
7f435c192000-7f435c193000 ---p 00000000 00:00 0 
7f435c193000-7f435c234000 rw-p 00000000 00:00 0 
7f435c234000-7f435c235000 ---p 00000000 00:00 0 
7f435c235000-7f435c2d6000 rw-p 00000000 00:00 0 
7f435c2d6000-7f435c2d7000 ---p 00000000 00:00 0 
7f435c2d7000-7f435c378000 rw-p 00000000 00:00 0 
7f435c378000-7f435c379000 ---p 00000000 00:00 0 
7f435c379000-7f435c41a000 rw-p 00000000 00:00 0 
7f435c41a000-7f435c41b000 ---p 00000000 00:00 0 
7f435c41b000-7f435c4bc000 rw-p 00000000 00:00 0 
7f435c4bc000-7f435c4bd000 ---p 00000000 00:00 0 
7f435c4bd000-7f435c55e000 rw-p 00000000 00:00 0 
7f435c55e000-7f435c55f000 ---p 00000000 00:00 0 
7f435c55f000-7f435c600000 rw-p 00000000 00:00 0 
7f435c600000-7f435c601000 ---p 00000000 00:00 0 
7f435c601000-7f435c6a2000 rw-p 00000000 00:00 0 
7f435c6a2000-7f435c6a3000 ---p 00000000 00:00 0 
7f435c6a3000-7f435c744000 rw-p 00000000 00:00 0 
7f435c744000-7f435c745000 ---p 00000000 00:00 0 
7f435c745000-7f435c7e6000 rw-p 00000000 00:00 0 
7f435c7e6000-7f435c7e7000 ---p 00000000 00:00 0 
7f435c7e7000-7f435c888000 rw-p 00000000 00:00 0 
7f435c888000-7f435c889000 ---p 00000000 00:00 0 
7f435c889000-7f435c92a000 rw-p 00000000 00:00 0 
7f435c92a000-7f435c92b000 ---p 00000000 00:00 0 
7f435c92b000-7f435c9cc000 rw-p 00000000 00:00 0 
7f435c9cc000-7f435c9cd000 ---p 00000000 00:00 0 
7f435c9cd000-7f435ca6e000 rw-p 00000000 00:00 0 
7f435ca6e000-7f435ca6f000 ---p 00000000 00:00 0 
7f435ca6f000-7f435cb10000 rw-p 00000000 00:00 0 
7f435cb10000-7f435cb11000 ---p 00000000 00:00 0 
7f435cb11000-7f435cbb2000 rw-p 00000000 00:00 0 
7f435cbb2000-7f435cbb3000 ---p 00000000 00:00 0 
7f435cbb3000-7f435cc54000 rw-p 00000000 00:00 0 
7f435cc54000-7f435cc55000 ---p 00000000 00:00 0 
7f435cc55000-7f435ee00000 rw-p 00000000 00:00 0 
7f435ee00000-7f435fd06000 r--p 00000000 fd:01 918193                     /usr/lib/locale/locale-archive
7f435fd7f000-7f435fd82000 r--p 00000000 fd:01 1444219                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f435fd82000-7f435fd99000 r-xp 00003000 fd:01 1444219                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f435fd99000-7f435fd9d000 r--p 0001a000 fd:01 1444219                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f435fd9d000-7f435fd9e000 r--p 0001d000 fd:01 1444219                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f435fd9e000-7f435fd9f000 rw-p 0001e000 fd:01 1444219                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f435fd9f000-7f435fe00000 rw-p 00000000 00:00 0 
7f435fe00000-7f435fe28000 r--p 00000000 fd:01 1443880                    /usr/lib/x86_64-linux-gnu/libc.so.6
7f435fe28000-7f435ffbd000 r-xp 00028000 fd:01 1443880                    /usr/lib/x86_64-linux-gnu/libc.so.6
7f435ffbd000-7f4360015000 r--p 001bd000 fd:01 1443880                    /usr/lib/x86_64-linux-gnu/libc.so.6
7f4360015000-7f4360019000 r--p 00214000 fd:01 1443880                    /usr/lib/x86_64-linux-gnu/libc.so.6
7f4360019000-7f436001b000 rw-p 00218000 fd:01 1443880                    /usr/lib/x86_64-linux-gnu/libc.so.6
7f436001b000-7f4360028000 rw-p 00000000 00:00 0 
7f436002a000-7f436005d000 r--s 00000000 fd:01 9962403                    /home/david/.rvm/rubies/ruby-2.7.1/bin/ruby
7f436005d000-7f436006b000 r--p 00000000 fd:01 1443884                    /usr/lib/x86_64-linux-gnu/libm.so.6
7f436006b000-7f43600e7000 r-xp 0000e000 fd:01 1443884                    /usr/lib/x86_64-linux-gnu/libm.so.6
7f43600e7000-7f4360142000 r--p 0008a000 fd:01 1443884                    /usr/lib/x86_64-linux-gnu/libm.so.6
7f4360142000-7f4360143000 r--p 000e4000 fd:01 1443884                    /usr/lib/x86_64-linux-gnu/libm.so.6
7f4360143000-7f4360144000 rw-p 000e5000 fd:01 1443884                    /usr/lib/x86_64-linux-gnu/libm.so.6
7f4360144000-7f4360146000 r--p 00000000 fd:01 1447161                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4360146000-7f436015a000 r-xp 00002000 fd:01 1447161                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f436015a000-7f4360173000 r--p 00016000 fd:01 1447161                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4360173000-7f4360174000 ---p 0002f000 fd:01 1447161                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4360174000-7f4360175000 r--p 0002f000 fd:01 1447161                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4360175000-7f4360176000 rw-p 00030000 fd:01 1447161                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4360176000-7f436017e000 rw-p 00000000 00:00 0 
7f436017e000-7f4360188000 r--p 00000000 fd:01 1447469                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.1
7f4360188000-7f43601e7000 r-xp 0000a000 fd:01 1447469                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.1
7f43601e7000-7f43601fe000 r--p 00069000 fd:01 1447469                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.1
7f43601fe000-7f43601ff000 r--p 0007f000 fd:01 1447469                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.1
7f43601ff000-7f4360200000 rw-p 00080000 fd:01 1447469                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.1
7f4360200000-7f436022d000 r--p 00000000 fd:01 10093545                   /home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7.1
7f436022d000-7f43604bd000 r-xp 0002d000 fd:01 10093545                   /home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7.1
7f43604bd000-7f43605b6000 r--p 002bd000 fd:01 10093545                   /home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7.1
7f43605b6000-7f43605bc000 r--p 003b5000 fd:01 10093545                   /home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7.1
7f43605bc000-7f43605bf000 rw-p 003bb000 fd:01 10093545                   /home/david/.rvm/rubies/ruby-2.7.1/lib/libruby.so.2.7.1
7f43605bf000-7f43605da000 rw-p 00000000 00:00 0 
7f43605eb000-7f43605ed000 r--p 00000000 fd:01 10355700                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/etc.so
7f43605ed000-7f43605f0000 r-xp 00002000 fd:01 10355700                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/etc.so
7f43605f0000-7f43605f2000 r--p 00005000 fd:01 10355700                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/etc.so
7f43605f2000-7f43605f3000 r--p 00006000 fd:01 10355700                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/etc.so
7f43605f3000-7f43605f4000 rw-p 00007000 fd:01 10355700                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/etc.so
7f43605f4000-7f43605f9000 r--p 00000000 fd:01 8794712                    /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/ext/ruby_prof/ruby_prof.so
7f43605f9000-7f4360601000 r-xp 00005000 fd:01 8794712                    /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/ext/ruby_prof/ruby_prof.so
7f4360601000-7f4360604000 r--p 0000d000 fd:01 8794712                    /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/ext/ruby_prof/ruby_prof.so
7f4360604000-7f4360605000 r--p 00010000 fd:01 8794712                    /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/ext/ruby_prof/ruby_prof.so
7f4360605000-7f4360606000 rw-p 00011000 fd:01 8794712                    /home/david/.rvm/gems/ruby-2.7.1@rubyprof/gems/ruby-prof-1.4.3/ext/ruby_prof/ruby_prof.so
7f4360606000-7f436060b000 rw-p 00000000 00:00 0 
7f436060b000-7f436060d000 r--p 00000000 fd:01 1442236                    /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f436060d000-7f436061e000 r-xp 00002000 fd:01 1442236                    /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f436061e000-7f4360624000 r--p 00013000 fd:01 1442236                    /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f4360624000-7f4360625000 ---p 00019000 fd:01 1442236                    /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f4360625000-7f4360626000 r--p 00019000 fd:01 1442236                    /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f4360626000-7f4360627000 rw-p 0001a000 fd:01 1442236                    /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f436062f000-7f4360630000 r--p 00000000 fd:01 10355771                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f4360630000-7f4360631000 r-xp 00001000 fd:01 10355771                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f4360631000-7f4360632000 r--p 00002000 fd:01 10355771                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f4360632000-7f4360633000 r--p 00002000 fd:01 10355771                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f4360633000-7f4360634000 rw-p 00003000 fd:01 10355771                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f4360634000-7f4360635000 r--p 00000000 fd:01 10355730                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f4360635000-7f4360636000 r-xp 00001000 fd:01 10355730                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f4360636000-7f4360637000 r--p 00002000 fd:01 10355730                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f4360637000-7f4360638000 r--p 00002000 fd:01 10355730                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f4360638000-7f4360639000 rw-p 00003000 fd:01 10355730                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f4360639000-7f436063a000 r--p 00000000 fd:01 10355708                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f436063a000-7f436063b000 r-xp 00001000 fd:01 10355708                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f436063b000-7f436063c000 r--p 00002000 fd:01 10355708                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f436063c000-7f436063d000 r--p 00002000 fd:01 10355708                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f436063d000-7f436063e000 rw-p 00003000 fd:01 10355708                   /home/david/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f436063e000-7f4360640000 rw-p 00000000 00:00 0 
7f4360640000-7f4360642000 r--p 00000000 fd:01 1443341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f4360642000-7f436066c000 r-xp 00002000 fd:01 1443341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f436066c000-7f4360677000 r--p 0002c000 fd:01 1443341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f4360678000-7f436067a000 r--p 00037000 fd:01 1443341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f436067a000-7f436067c000 rw-p 00039000 fd:01 1443341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fff85a36000-7fff86235000 rw-p 00000000 00:00 0                          [stack]
7fff862b2000-7fff862b6000 r--p 00000000 00:00 0                          [vvar]
7fff862b6000-7fff862b8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]


Aborted (core dumped)
```

</details>

Core dump is available if needed.

**Comment by cfis** [comment]
Thanks for the report and test case - I can replicate the crash.
