### ISSUE TITLE
ruby-prof (1.7.1) x64-mingw-ucrt trying to link ELF libraries.

### ISSUE THREAD

**Issue by Erquint** [ruby-prof/ruby-prof#335]
```
PS C:\Windows\System32> (Get-CimInstance Win32_OperatingSystem).Caption
Microsoft Windows 10 Pro
PS C:\Windows\System32> (Get-CimInstance Win32_OperatingSystem).Version
10.0.19045
PS C:\Windows\System32> gem info ruby-prof

*** LOCAL GEMS ***

ruby-prof (1.7.1)
    Platform: x64-mingw-ucrt
    Author: Shugo Maeda, Charlie Savage, Roger Pack, Stefan Kaes
    Homepage: https://github.com/ruby-prof/ruby-prof
    License: BSD-2-Clause
    Installed at: C:/Ruby32-x64/lib/ruby/gems/3.2.0

    Fast Ruby profiler
PS C:\Windows\System32> ruby-prof G:\Projects\rb\DNS_to_DoH_proxy\main.rb 185.36.140.84
<internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- ruby_prof.so (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ruby-prof-1.7.1-x64-mingw-ucrt/lib/ruby-prof.rb:9:in `rescue in <top (required)>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ruby-prof-1.7.1-x64-mingw-ucrt/lib/ruby-prof.rb:5:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ruby-prof-1.7.1-x64-mingw-ucrt/bin/ruby-prof:4:in `<top (required)>'
        from C:/Ruby32-x64/bin/ruby-prof:36:in `load'
        from C:/Ruby32-x64/bin/ruby-prof:36:in `<main>'
<internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- 3.2/ruby_prof.so (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ruby-prof-1.7.1-x64-mingw-ucrt/lib/ruby-prof.rb:7:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ruby-prof-1.7.1-x64-mingw-ucrt/bin/ruby-prof:4:in `<top (required)>'
        from C:/Ruby32-x64/bin/ruby-prof:36:in `load'
        from C:/Ruby32-x64/bin/ruby-prof:36:in `<main>'
```

**Comment by cfis** [comment]
Hmm, do you mean that the library is called ruby_prof.so? Ruby extensions on windows use .so as the extension, not .dll. So that is as expected. Or do you mean something else?

Sounds like you are missing that file (should be ruby-prof/lib/3.2/ruby_prof.so. It is included in the mingw version download of ruby-prof. Otherwise it should be built on install. How did you install ruby-prof?

**Comment by Erquint** [comment]
You're right, I did assume ELF judting by `.so`.  
I simply ran `gem install ruby-prof`.  
Are there additional steps that I needed to take?

**Comment by Erquint** [comment]
The instruction didn't make it very clear, to be frank.

> If you are running Linux or Unix you'll need to have a C compiler installed so the extension can be built when it is installed. If you are running Windows, then you should install the Windows specific gem or install install [devkit](https://rubyinstaller.org/add-ons/devkit.html).

— https://ruby-prof.github.io/#installation

I'm assuming that the "Windows specific gem" is referring to the version/distribution that has been automatically installed in this case.

And that "install install" seems like an editing mistake, but I do have the MSYS2 devkit if that's what it's suggesting.

**Comment by cfis** [comment]
Ok, what's not clear about the instructions?

And what version of the gem did you install?

`gem list ruby-prof`

Is the mingw version or the source version? If it is the source version then it will try to compile the extension on installation. If that fails the gem should not install.

If you have the mingw version, then go look at the ruby-prof installation directory and see if the ruby_prof.so file is there. The last release only included a build for Ruby 3.3, so that is likely your problem. You'll need to use Ruby 3.3 or alternatively compile the gem. To do that, open a devkit prompt (not powershell, not CMD) and install the gem `gem install --platform ruby ruby-prof` and that should build the extension.

**Comment by Erquint** [comment]
> Ok, what's not clear about the instructions?

Oh, I just pointed it out in the previous message.
- "Windows specific gem" is an unclear reference.
  It can't tell if it's suggesting I use another gem instead of `ruby-prof` and in that case — which.  
  More likely, it's to specify versions, not distinct gems, but at that point I'm already confused, especially considering that all of the versions I get when running `gem info -r ruby-prof` already include either `mswin` or `mingw` anyway.
```pwsh
PS C:\Windows\System32> gem info -r ruby-prof

*** REMOTE GEMS ***

ruby-prof (1.7.1, 1.4.3, 0.12.1, 0.8.1, 0.7.3, 0.5.2)
    Platforms:
        0.5.2: mswin32
        0.7.3: x86-mswin32-60
        0.8.1: x86-mswin32
        0.12.1: x86-mingw32
        1.4.3: x64-mingw32
        1.7.1: ruby, x64-mingw-ucrt
    Author: Shugo Maeda, Charlie Savage, Roger Pack, Stefan Kaes
    Homepage: https://github.com/ruby-prof/ruby-prof
    License: BSD-2-Clause

    Fast Ruby profiler
```
- "install install" is unclear for obvious grammatical reasons as part of that already confusing sentence.

> And what version of the gem did you install?

It's in the title and the shell output in the initial message.  
> `ruby-prof (1.7.1) x64-mingw-ucrt`

---

> see if the ruby_prof.so file is there

`C:\Ruby32-x64\lib\ruby\gems\3.2.0\gems\ruby-prof-1.7.1-x64-mingw-ucrt\lib\3.3\ruby_prof.so` is present. No other `ruby_prof.so` files are present anywhere.

> open a devkit prompt (not powershell, not CMD)

Not sure what's a "devkit prompt" as own discrete thing, but seems like it's integrated into system shells just fine through MSYS2. Built from `pwsh` (PowerShell Core).

```pwsh
PS C:\Ruby32-x64\lib\ruby\site_ruby\3.2.0> gem install ruby-prof --platform ruby
Fetching ruby-prof-1.7.1.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed ruby-prof-1.7.1
Parsing documentation for ruby-prof-1.7.1
Installing ri documentation for ruby-prof-1.7.1
Done installing documentation for ruby-prof after 0 seconds
1 gem installed

PS C:\Ruby32-x64\lib\ruby\site_ruby\3.2.0> ruby-prof
ruby_prof 1.7.1
Usage: ruby-prof [options] <script.rb> [--] [profiled-script-command-line-options]
```

Just CLI-ran a test profile of my multithreaded script and ruby-prof spent several minutes overflowing my terminal with a lengthy report that I'll figure out how to direct into a file for actual reading tomorrow. This is to say: it seems to be launching fine now.

Maybe it's worth including `gem install ruby-prof --platform ruby` as a Windows instruction rather than `you should install the Windows specific gem or install install`.

Thank you for advice.

**Comment by cfis** [comment]
Right you want x64-mingw-ucrt, but I generally only make builds for the latest version of Ruby.  And yes, the msys2 prompt is correct. 

Thanks for the documentation feedback. If you'd like to update it to be more clear, happy to review a PR and merge it in. Otherwise I'll try to update it based on your feedback.

**Comment by Erquint** [comment]
Point me to your gh-pages branch. I'm struggling to locate it.

**Comment by cfis** [comment]
https://github.com/ruby-prof/ruby-prof.github.io

**Comment by Erquint** [comment]
Oh, it's a separate repo. Will look into rewording it later.
